### ISSUE TITLE
Возможность выбора нескольких значений при создании проверки

### ISSUE THREAD

**Issue by IgorPolyakov** [IgorPolyakov/TheHoneydew#14]
- [ ]  Новая проверка :: Категория проверки

- [ ] Новая проверка :: Установленные нарушения

- [ ] Новая проверка :: Меры реагирования

**Comment by Vexarr** [comment]
Исправить выпадающие списки, на списки с чекбоксами.

**Comment by Vexarr** [comment]
Значения будут храниться в виде текста.

**Comment by IgorPolyakov** [comment]
Можно попробовать этот вариант
http://www.jqueryscript.net/demo/jQuery-Multiple-Select-Plugin-For-Bootstrap-Bootstrap-Multiselect/
