### ISSUE TITLE
Проверяющие не изменяются

### ISSUE THREAD

**Issue by 555Shaman555** [IgorPolyakov/TheHoneydew#26]
Проверяющие не изменяются (и в списке всех проверяющих, и со страницы подрбной информации)
https://kru.keva.su/inspectors

**Comment by 555Shaman555** [comment]
![default](https://user-images.githubusercontent.com/23053342/27768513-a8854456-5f3f-11e7-88cd-fcdb5a2054e6.png)

**Comment by Layz1337** [comment]
Проблема не воспроизвелась
