### ISSUE TITLE
Записи "Организация" не изменяются

### ISSUE THREAD

**Issue by 555Shaman555** [IgorPolyakov/TheHoneydew#28]
Ошибка при редактировании записей "Организации"
https://kru.keva.su/organizations

**Comment by 555Shaman555** [comment]
![default](https://user-images.githubusercontent.com/23053342/27768560-d4ce4c64-5f40-11e7-944e-bb586b82500e.png)

**Comment by Layz1337** [comment]
Проблема не воспроизвелась
