### ISSUE TITLE
Некорректное отображение при создании "Новая проверка"

### ISSUE THREAD

**Issue by 555Shaman555** [IgorPolyakov/TheHoneydew#29]
количество проверок (строка обрезана)
количество томов (строка обрезана)
https://kru.keva.su/checks/new

**Comment by IgorPolyakov** [comment]
@555Shaman555  - Можешь скриншот приложить, у меня не воспроизводится

**Comment by 555Shaman555** [comment]
![default](https://user-images.githubusercontent.com/23053342/27686446-f9bc03ea-5cfc-11e7-8f17-8e10a7e12ee0.png)

**Comment by 555Shaman555** [comment]
![default](https://user-images.githubusercontent.com/23053342/27686456-087b1100-5cfd-11e7-8b10-e51d4b655eae.png)

**Comment by IgorPolyakov** [comment]
![image](https://user-images.githubusercontent.com/2613581/27767597-76520334-5f26-11e7-8ac6-30901f7bed6b.png)
не воспроизводиться(
