### ISSUE TITLE
Массовое удаление контрольных дел

### ISSUE THREAD

**Issue by 555Shaman555** [IgorPolyakov/TheHoneydew#32]
При удалении одного контрольного дела удалилось и другое
https://kru.keva.su/reports

**Comment by Layz1337** [comment]
Хм... У меня все нормально. то делал для того, чтобы удалилось несколько дел?

**Comment by Layz1337** [comment]
Проблема не воспроизвелась

**Comment by 555Shaman555** [comment]
![default](https://user-images.githubusercontent.com/23053342/27768586-510b85e4-5f41-11e7-8e02-3e322d20d773.png)
Перед нажатием кнопки удаления было 3 контрольных дела
