### ISSUE TITLE
Добавить функционал к кнопкам "Расширить"

### ISSUE THREAD

**Issue by Layz1337** [IgorPolyakov/TheHoneydew#43]
Пока они ничего не делют
![default](https://user-images.githubusercontent.com/20367569/27804933-cbe43c14-605b-11e7-8a79-e8fab059fa75.png)

**Comment by IgorPolyakov** [comment]
А какой функционал, собственно, можно прикрутить?

**Comment by Layz1337** [comment]
Не знаю. Можно, например, чтобы по нажатию на нее выползала информационная сводка по пункту (Ну я даже не знаю, что туда можно засунуть. Сколько всего записей, дата последнего изменения, еще что-нибудь).
А можно просто их выпилить.
