### ISSUE TITLE
Странное поведение чекбоксов при создании проверки или контрольного дела

### ISSUE THREAD

**Issue by IgorPolyakov** [IgorPolyakov/TheHoneydew#44]
![o7dtk5on92](https://user-images.githubusercontent.com/2613581/27815931-6be4fb94-60b2-11e7-931e-80945d01bb0c.gif)

**Comment by Layz1337** [comment]
Если кликать на сами поля, а не надписи -- то норм. Попробуем поправить.

**Comment by Layz1337** [comment]
Лейблы должны быть разными
![default](https://user-images.githubusercontent.com/20367569/27818760-45d0cc58-60c1-11e7-926e-ae4f26235b6b.png)

**Comment by IgorPolyakov** [comment]
Нужно посмотреть как simpleform генерит лейблы и id

**Comment by Layz1337** [comment]
Уже в документации шарюсь, но я не силен в этом.

**Comment by Layz1337** [comment]
Бага, связанная с русскими символами

**Comment by IgorPolyakov** [comment]
"Сиди спокойно на берегу реки, и мимо проплывет труп твоего врага."
![image](https://user-images.githubusercontent.com/2613581/31263292-81fb0734-aa8b-11e7-85ee-3f2fed79f7bd.png)

Бага исправлена! Если я правильно понял - новая версия Ruby оперирует не только ASCII символами, а подгружает UTF-8.
