### ISSUE TITLE
Отрицательное колличество проверок

### ISSUE THREAD

**Issue by IgorPolyakov** [IgorPolyakov/TheHoneydew#45]
![default](https://user-images.githubusercontent.com/2613581/27816012-eb389234-60b2-11e7-9f0d-6a4ae5a8926f.png)

Думаю, нужно не только фронт поправить, но и в БД внести соответствующие ограничение

**Comment by IgorPolyakov** [comment]
добавить валидацию, validates :age, numericality: { less_than_or_equal_to: 100,  only_integer: true }

**Comment by Layz1337** [comment]
Не та переменная
