### ISSUE TITLE
New front-end

### ISSUE THREAD

**Issue by IgorPolyakov** [IgorPolyakov/TheHoneydew#63]
http://materializecss.com/

**Comment by ManizhaM** [comment]
https://github.com/mkhairi/materialize-sass
installation for rails

**Comment by IgorPolyakov** [comment]
Or move from bootstrap 3 to 4

https://github.com/twbs/bootstrap-rubygem

**Comment by IgorPolyakov** [comment]
version 2.0 uses bootstrap 4
