### ISSUE TITLE
Некорректное поведение при создании новой проверки

### ISSUE THREAD

**Issue by stelse** [IgorPolyakov/TheHoneydew#67]
Если при создании проверки указать в поле "Количество проверок" значение 9999999999 (десять цифр 9), то вываливается сообщение
![default](https://user-images.githubusercontent.com/20367566/31316111-ba3a3c70-ac50-11e7-83f0-abf2d5520493.png)

**Comment by IgorPolyakov** [comment]
Нужно задать максимальный лимит числа в simple_form
