### ISSUE TITLE
"Номер контрольного дела" занимает слишком много места

### ISSUE THREAD

**Issue by Layz1337** [IgorPolyakov/TheHoneydew#68]
![default](https://user-images.githubusercontent.com/20367569/31493219-6642253a-af78-11e7-8c9d-ab38460d855f.png)
![default](https://user-images.githubusercontent.com/20367569/31493231-8074bdd2-af78-11e7-92a2-59cdd7b098d2.png)

**Comment by Layz1337** [comment]
Есть вариант сократить как "№ к. дела" или "№ к. д."

**Comment by IgorPolyakov** [comment]
"№ к. д." - сообщение от Гуляева
