### ISSUE TITLE
Перевод страницы

### ISSUE THREAD

**Issue by 555Shaman555** [IgorPolyakov/TheHoneydew#82]
При переключении языка на английский, страница http://91.210.186.187:8080/en/dashboard/report не меняет язык 
![default](https://user-images.githubusercontent.com/23053342/39136125-bb29d872-4744-11e8-8cd2-7a925b027342.png)

**Comment by IgorPolyakov** [comment]
возможно эта [документация](http://rusrails.ru/rails-internationalization-i18n-api#internatsionalizatsiya-i-lokalizatsiya) поможет
